# Generated by Django 2.1.5 on 2019-01-27 23:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='changed')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('time_to', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2500)),
                ('status', models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subsribed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_subsribed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
